### ISSUE TITLE
感谢楼主

### ISSUE THREAD

**Issue by y1024** [goomadao/MSI-MAG-B460M-MORTAR-WIFI-OpenCore-EFI#1]
使用楼主，可以直接使用，弱弱的问下，cpu变频正常么？

**Comment by goomadao** [comment]
正常
![image](https://user-images.githubusercontent.com/39483078/125198643-5476ac00-e295-11eb-8508-2befc9a05ee9.png)
![image](https://user-images.githubusercontent.com/39483078/125198666-6fe1b700-e295-11eb-8270-9345397908c5.png)

**Comment by y1024** [comment]
嗯 谢谢

**Comment by y1024** [comment]
需要加入 CPUFriend 么？

**Comment by y1024** [comment]
方便添加下qq么。

**Comment by goomadao** [comment]
> 需要加入 CPUFriend 么？

不需要，所有用到的kext都在仓库里面了

**Comment by y1024** [comment]
嗯 谢谢 方便加下Q么 想有偿帮忙定制个 10.15.7的 efi。谢谢。

**Comment by goomadao** [comment]
> 嗯 谢谢 方便加下Q么 想有偿帮忙定制个 10.15.7的 efi。谢谢。

不定制哈，抱歉
